name: 花金だーワッショーイ！テンションAGEAGEマック
permissions: {}
on:
  schedule:
    - cron: '0 9 * * 5' # Friday 18:00 (JST)
jobs:
  tweet:
    runs-on: ubuntu-latest
    steps:
    - uses: noweh/post-tweet-v2-action@v1.0
      with:
        message: "花金だーワッショーイ！テンションAGEAGEマック"
        consumer-key: ${{ secrets.TWITTER_CONSUMER_KEY }}
        consumer-secret: ${{ secrets.TWITTER_CONSUMER_SECRET }}
        access-token: ${{ secrets.TWITTER_ACCESS_TOKEN }}
        access-token-secret: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
        bearer-token: ${{ secrets.TWITTER_BEARER_TOKEN }}
