name: test
on:
  workflow_dispatch:
permissions: {}
jobs:
  tweet:
    runs-on: ubuntu-latest
    steps:
    - uses: noweh/post-tweet-v2-action@v1.0
      with:
        message: "Hi, this is a test!"
        consumer-key: ${{ secrets.TWITTER_CONSUMER_KEY }}
        consumer-secret: ${{ secrets.TWITTER_CONSUMER_SECRET }}
        access-token: ${{ secrets.TWITTER_ACCESS_TOKEN }}
        access-token-secret: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
        bearer-token: ${{ secrets.TWITTER_BEARER_TOKEN }}
